# SPDX-FileCopyrightText: 2024 Stichting Health-RI
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Publish and Deploy main

on:
    workflow_run:
      workflows: ["Run Tests"]
      branches: [main]
      types:
        - completed

jobs:
    ort:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses: oss-review-toolkit/ort-ci-github-action@81698a977ebcf51bb3d6ef5c6a04220cf60d3bde
              with:
                  allow-dynamic-versions: "true"
                  fail-on: "issues"
                  run: "cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results"

